version: "3.8"
services:
  service1:
    build: ./service1/
    # This creates a link to the host computer's localhost, accessible at host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
    environment:
      OTEL_SERVICE_NAME: service1
  service2:
    build: ./service2/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3002:3002"
    environment:
      OTEL_SERVICE_NAME: service2
