version: "3.8"
services:
  service1:
    image: demo-service1:latest
    ports:
      - "3001:3001"
      - "3002"
      - "4319"
    environment:
      OTEL_SERVICE_NAME: service1
  service2:
    image: demo-service2:latest
    ports:
      - "3002:3002"
      - "3001"
      - "4319"
    environment:
      OTEL_SERVICE_NAME: service2
