version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    deploy:
      resources:
        limits:
          memory: 4Gb
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9200:9200"
      - "9300:9300"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "14250" # where gateway sends to
      - "14269:14269"
    depends_on:
      - elasticsearch
    restart: always

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    depends_on:
      - elasticsearch
    restart: always

  grafana:
    image: teamhypha/hypha-grafana:latest
    build: ./hypha-grafana/
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  collector:
    image: teamhypha/hypha-collector:latest
    build: ./hypha-collector/
    command: ["--config", "/otel-config.yaml"]
    ports:
      - "4317:4317" # grpc  host:container
    depends_on:
      - jaeger-collector
      - loki

  loki-read:
    image: teamhypha/hypha-loki:latest
    build: ./hypha-loki/
    command: "-config.file=/etc/loki/config-local.yaml -target=read"
    depends_on:
      - minio

  loki-write:
    image: teamhypha/hypha-loki:latest
    build: ./hypha-loki/
    command: "-config.file=/etc/loki/config-local.yaml -target=write"
    depends_on:
      - minio

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000"
    volumes:
      - minio_data:/data

  loki:
    image: teamhypha/hypha-loki-nginx:latest
    build: ./hypha-loki-nginx/
    depends_on:
      - loki-read
      - loki-write
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_RESOLVER=127.0.0.11
      - NGINX_LOKI_READ=http://loki-read:3100
      - NGINX_LOKI_WRITE=http://loki-write:3100
    ports:
      - "3100:3100"

  nginx:
    image: teamhypha/hypha-ui-nginx:latest
    build: ./hypha-ui-nginx/
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_RESOLVER=127.0.0.11
      - NGINX_SERVER=grafana:3000
    ports:
      - "80:80"

volumes:
  es_data:
  minio_data:
  grafana_data:
