receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    format: json
    labels:
      attributes:
        level: "level"
      resource:
        service: "service"
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/tempo]
    logs:
      receivers: [otlp]
      exporters: [logging, loki]
