receivers:
  filelog:
    include: [./services/*/logs/*.json]
    resource: { service: "service0" }
    # operators:
    #   - type: json_parser
    #   - type: trace_parser
    #     trace_id:
    #       parse_from: trace_id
    #     span_id:
    #       parse_from: span_id
    #     trace_flags:
    #       parse_from: trace_flags
exporters:
  logging:
  otlp:
    endpoint: 0.0.0.0:4317
    tls:
      insecure: true
service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging, otlp]
