---
auth_enabled: false
server:
  http_listen_port: 3100
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - loki-read.hypha-backend.local:7946
    - loki-write.hypha-backend.local:7946
schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
    instance_interface_names:
      - "eth1"
ruler:
  storage:
    s3:
      bucketnames: loki-ruler
