version: "3"
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - ./loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - 3100:3100

  # tempo:
  #   image: grafana/tempo:latest
  #   command: ["-config.file=/etc/tempo.yaml"]
  #   volumes:
  #     - ./tempo-local.yaml:/etc/tempo.yaml
  #     # - ./tempo-data:/tmp/tempo
  #   ports:
  #     - "3200:3200" # tempo
  #     - "4317" # otlp grpc

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  otel-collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config", "/otel-config.yaml"]
    ports:
      - "4319:4317" # grpc  host:container
    depends_on:
      - jaeger-all-in-one
      - loki
      - grafana
