receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
  fluentforward:
    endpoint: "0.0.0.0:8006"
processors:
  attributes:
    actions:
      - key: fluent_tag
        value: tail.0
        action: insert
exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      attributes:
        fluent.tag: "fluent_tag"
        file.name: "file_name"
        service: "service"
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging, jaeger, otlp]
    logs:
      receivers: [fluentforward, otlp]
      exporters: [logging, loki]
