receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
  filelog:
    include: [./logs/*.json]
    include_file_name: false
    operators:
      - type: json_parser
      - type: add
        field: $$resource.service
        value: $OTEL_SERVICE_NAME
      - type: trace_parser
        TraceId:
          parse_from: trace_id
        SpanId:
          parse_from: span_id
        TraceFlags:
          parse_from: trace_flags
processors:
  attributes:
    actions:
      - key: service
        value: $OTEL_SERVICE_NAME
        action: insert
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "host.docker.internal:4319" # this references the host's localhost (see docker-compose)
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging, otlp]
    logs:
      receivers: [filelog]
      exporters: [logging, otlp]
