{
 "title": "Errors",
 "description": "An overview of logs with errors",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service Name", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Logs By Level",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$service\"}[$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Errors by Service",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({level=\"error\"}[$__range]) or count_over_time({level=~\".+\"}[$__range]) * 0)"
    }
   ]
  },
  {
   "title": "Logs with Errors",
   "type": "logs",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{level=\"error\", service=~\"$service\"}"
    }
   ]
  }
 ]
}